name = "ManaromRegistry"
uuid = "1bece238-766f-4185-87df-1dc9911064e9"
repo = "https://github.com/Manarom/ManaromRegistry.git"

[packages]
f583effd-a810-4e6b-b1e2-2b4349a685d7 = { name = "RadiationPyrometers", path = "R/RadiationPyrometers" }
